### ISSUE TITLE
Interaction with wye's causing process not to halt

### ISSUE THREAD

**Issue by alissapajer** [scalaz/scalaz-stream#316]
I've found an issue where an interaction between some `wye`s and `until`s is causing certain code to behave inconsistently. Specifically, sometimes the provided example process hangs when run, and sometimes it halts. I expect it to always halt.

I've run the following example on current `master` as well as on branch `bug/step-runAsync` (pushed to my fork), which contains the fixes/hacks related to #290. On both branches, I see the same behaviour. This rules out two possibilities: (1) this is the same issue as #290 and (2) the fix for issue #290 created this bug.

I'd very much like to provide a cleaner (i.e. smaller) example, because what's below is admittedly, well, messy :/ But as of now I haven't been able reduce this any furtuer. If I rewrite it to remove any of the `wye` usages, then the process always halts, as expected.

Here's an overview of what's happening in the example: We send `terminationData: Process[Task, String]` through the sink `aggregate: Sink[Task, String]`.  Now `aggregate` enqueues this `terminationData` to `queue`, and then merges that enqueue process with a second process `merged`, which dequeues the queue through another sink called `terminator`, which sets a boolean `signal`, which should be triggering the output process to halt. `empty` and `stuff` are in there because, without them, the bug doesn't present itself.

```scala
import scala.language.postfixOps
import scalaz.concurrent._

class Test {
  val expected = "data"
  val signal = async.signalOf[Boolean](false)
  val queue = async.boundedQueue[String](10)

  val terminator: Sink[Task, String] = Process {
    (s: String) => signal set (s == expected)
  }

  val aggregate: Sink[Task, String] = {
    val merged: Process[Task, String] = {
      val empty = Process.empty[Task, String]
      val boundedDequeue = empty merge queue.dequeue to terminator    // required: empty merge ...
      val stuff = Process constant "stuff" until signal.continuous    // required: until signal.continuous
      stuff.wye(boundedDequeue.drain)(wye.mergeHaltBoth)              // required: the entire wye
    }

    queue.enqueue.wye(merged.drain)(wye.mergeHaltBoth)                // required: the entire wye
  }

  val terminationData: Process[Task, String] = Process constant expected until signal.continuous
  val res: Process[Task, Unit] = terminationData to aggregate

  println("____________STARTING TEST")

  implicit val scheduler = scalaz.stream.DefaultScheduler
  res.run.timed(3000).run
  
  println("____________FINISHED TEST")
}
```
To reproduce, run `new Test` in a console. I'm seeing approximately a 20% hang rate, meaning that the process completes 80% of the time, and hangs 20% of the time. 

I'm working right now to debug this further in the `scalaz-stream` code. I believe that the `empty merge queue.dequeue` is a key part to this issue, as when you litter the example with `onComplete` printlns, it's this `merge` that's not halting. I'll reply to this ticket as I learn more.

**Comment by alissapajer** [comment]
Some things I've determined:

(1) `step` is not infinite looping. We enter into step a few times, but ultimately leave it. Then we sit and do something (or nothing?) until the 3 second timeout is reached.

(2) `tee.until` receives the `true` value whether the test hangs or doesn't.

(3) Consider the following:
```scala
val boundedDequeue = empty merge queue.dequeue onComplete Process.eval_(Task.delay(println("boundedDequeue minus terminator COMPLETE"))) to terminator onComplete Process.eval_(Task.delay(println("boundedDequeue COMPLETE")))
```
When the test hangs, only the "first" `onComplete` is reached. When the test doesn't hang, both `onComplete`s are reached. What lies between is `through` (`to` is an alias for `through`).

(4) When you remove `terminator` entirely (delete `to terminator`) and replace `empty` with
```scala
val empty = Process.eval_(signal set true) ++ Process.empty[Task, String]
```
then the process never hangs. This points toward `through` being part of the problem.

**Comment by alissapajer** [comment]
[Thread dump](https://gist.github.com/alissapajer/299fe84e1924e5a49569) taken while hanging. Only references to scalaz are in lines 148-150.

**Comment by pchlupacek** [comment]
@alissapajer I just fixed that isssue with step and wye. Also in the code you have been trying this with, there was slight change in behaviour that runAsync emitted `empty`, that was not the cause before. 
Would be excellent if you can try with fixed code in pr branch  now and see if the problem persist.

**Comment by alissapajer** [comment]
@pchlupacek I just tried this example against your latest PR'd `bug/step-runAsync` branch, and the problem still persists :/  2 out of 10 runs of the example hung.

**Comment by alissapajer** [comment]
Note to self: try this example with different numbers of processors!

**Comment by edwinchoi** [comment]
This example seems problematic.

Both the producer and consumer are preempted by signal and are attached to the enqueue/dequeue sides asynchronously. When both producer and consumer terminate, there's nothing left to observe the effects. This is only an issue when there is nondeterminism (using sequential strategy does not exhibit the same problem).

I suspect what is happening is that boundedDequeue is terminating after aggregate and merged, and boundedDequeue is active when merged attempts to interrupt it. When that happens, the wye needs to run the (n+1) step to send the termination upstream (not sure if this is intended, but it's caused me some headaches in the past).

If you cleanup the queue on termination and halt the Y on the queue side only, this issue does not occur.
Obviously doesn't address the fact that this example doesn't halt, but I don't think it should be expected to without code to signal completion through the queue.

**Comment by edwinchoi** [comment]
Giving it a bit more thought, I agree this *should* halt.

**Comment by edwinchoi** [comment]
The problem is with the implementation of wye.

I added some logging to wye and found that it's being told to terminate twice -- haven't looked too deeply into why. In other words, the actor is being sent `DownDone` twice.
When the actor handles `DownDone`, it ignores any existing callback in `out` and assigns a new callback to `out`.

What's happening is that the second `DownDone` is replacing the callback from the first `DownDone`, so the first terminate request never completes.

This only appears to affect the wye internally - `onHalt` does not get called multiple times.

Changing the implementation to chain the callbacks resolves the halting issue.

**Comment by edwinchoi** [comment]
Correction: duplicate termination is only an issue on master. Seems due to changes mentioned by @pchlupacek.

On 0.6a branch, the inner processes are actually stuck -- blocked waiting on dequeue.

**Comment by edwinchoi** [comment]
Here is a shorter example to reproduce this issue:

```scala
object Test extends App {
  import scalaz.stream._
  import Process._

  implicit val scheduler = DefaultScheduler

  for (i <- 1 to 100) {
    println(s"run $i")
    val q = async.unboundedQueue[Unit]
    q.enqueueOne(()).run

    val process = ((q.dequeue merge halt).once wye halt)(wye.mergeHaltBoth)
    process.run.timed(3000).run
    println("done")
  }

  println("all done")
}
```

Tested this against `master`, current release, and `step-runAsync` - occurs on all.

I've narrowed down the issue to the cleanup code for `wye`, which is being called twice by `runAsync` -- first call is on interrupt, second when `await` completes. The second call clobbers the callback for the first, resulting in the hung process.

**Comment by pchlupacek** [comment]
@edwinchoi Thanks for observing this. The issue raises from the way how runAsync works. Iw we have an await that is interrupted we clean up the cleanups before the await was run, and then, we run any cleanups after await completes just from that last await's rcv. The reason for this is that interrupted await may not complete at all (thats why we must run cleanups before it) and may complete with allocating the resources. 

I know this sounds strange, but unless we will find how to do interruption deterministics, in current signatures I do not know of better solution. 

So the fix for that would be to fix wye that it can run its cleanup and DownDone only once, whichever comes first wins. This is imho not how it is implemented now.

Please see this runAsync code, which I think is nearly correct. Now we have to fix wye: 

https://gist.github.com/pchlupacek/880a01e170afe897422d

**Comment by edwinchoi** [comment]
@pchlupacek while I understand why the interrupt is there, I don't really agree with how it's being done...

It seems like the assumption is that the cleanup can clear what would otherwise be a deadlock.
Something like:
```scala
val latch = new CountDownLatch(1)
eval(Task.delay(latch.await()))
  .onComplete(Task.delay(latch.countDown()))
```

While this does work, it uses onComplete in a way that is inconsistent with the documentation and even its name.

IMO interrupt should be kept as a separate concept from termination. The cleanup code is not being called because the process has halted, as would be the case for a synchronous process. It's being called as a means to unblock a blocked request, after which the process halts.

Something like 'onPreempt' would allow the decision on how to react to an interrupt request to be made locally, which is where it should be.

(I thought I read somewhere about an interruptible task, but I can't seem to find it?)

Anyway, for the short term, I agree `wye` should be fixed so that multiple applications of `onComplete` don't clobber one another.

Would you like me to create a PR? Should be able to get to it in a couple days..

**Comment by djspiewak** [comment]
> Would you like me to create a PR? Should be able to get to it in a couple days..

I can't speak for Pavel, but I can tell you that *we* (@alissapajer and I) would most definitely make use of such a PR.  So…pretty please?  :-D

**Comment by pchlupacek** [comment]
@edwinchoi please feel free to fix the wye. If you do a PR I can then take it with fixed runAsync and step and hopefully that will fix the issue. 

I am not getting fully your arguments about onComplete, and we have to discuss it. The problem with interruption arises when you have asynchronous code that may never complete, such as awaiting the queue that will never receive item, needs to be interrupted.

The decision was made that hence you may not see full process at point where you put cleanups in (you don't know if async action is involved) we would not ask user to use two combinators that will eventually have different behaviour on interruption, that from user perspective may not been `visible` at all. 

i.e.
```scala
val q = async.boundedQueue()
// right side block asynchronously on queue that never get anything in
// so we need to interrupt
Process.awakeEvery(1.second).either(q.dequeue).take(1)

// this allocates resources, so we need to call the asynchronous cleanup eventually
// as we don't know whichever side was run, potentially both
Process.awakeEvery(1.second).flatMap(_=>allocate1()).onComplete(cleanup1)
.either(Process.awakeEvery(1.second).flatMap(_=>allocate2()).onComplete(cleanup2))
.take(1)

```

**Comment by pchlupacek** [comment]
Just to add a bit, I think the whole interruption behaviour may be imporved significantly, but that will require to touch future and task perhaps quite heavily. This was behind the motivations to include scalaz-concurrent in scalaz-stream, So we can properly fix that.

**Comment by djspiewak** [comment]
As an interesting sidebar, these sorts of hangs are relatively easy to replicate even dodging `wye` entirely!  Out of desperation, we wrote `wye.interrupt`, `wye.merge` and `wye.mergeHaltBoth` on top of strictly `mergeN`, without any other concurrency primitives.  Still got deadlocks.  Deadlocks in slightly different places, but deadlocks nonetheless.  It's interesting to note that `mergeN` does appear to do a significantly better job with fairness, even when used in this combinatorial fashion.

In any case, that definitely fingers `runAsync` as a serious problem, even above and beyond the issues with `wye`.

**Comment by edwinchoi** [comment]
@djspiewak couldn't agree more. I've removed all uses of wye and anything nondeterministic in my own code, except async._, because of the bugs and weakened invariants.

@pchlupacek and @djspiewak I'll do the PR over the weekend

**Comment by pchlupacek** [comment]
@edwinchoi can you perhaps put a list of weakened invariants? Would be nice to either list them, or strengthen them. 
I want to have wye "durable" as much as possible.

**Comment by edwinchoi** [comment]
Created the PR, sorry for delay. Will follow up later with my thoughts on making `wye` durable.

**Comment by alissapajer** [comment]
I'd like to verify that this has been fixed. I'll reclose if it's indeed been resolved.

**Comment by alissapajer** [comment]
Ok, I've verified that @edwinchoi 's PR #324 (which is already in master) fixes this issue. Closing issue. Thanks!
