### ISSUE TITLE
signalOf() doesn't "Set" as far as compareAndSet() is concerned

### ISSUE THREAD

**Issue by psnively** [scalaz/scalaz-stream#389]
Constructing a Signal with signalOf(), then using compareAndSet() reveals that the "old" value is None:

```scala
> console
[warn] Credentials file /Users/psnively/.bintray/.credentials does not exist
[info] Starting scala interpreter...
[info] 
import scalaz.stream._
Welcome to Scala version 2.11.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_31).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import async._
import async._

scala> val s = signalOf[Int](5)
s: scalaz.stream.async.mutable.Signal[Int] = scalaz.stream.async.mutable.Signal$$anon$1@6231f63f

scala> s.compareAndSet(x => { println(s"Old value = $x"); Some(10) })
res0: scalaz.concurrent.Task[Option[Int]] = scalaz.concurrent.Task@1bb740cc

scala> res0.run
Old value = None
res1: Option[Int] = Some(10)
```

.get() works, and compareAndSet() works if you .set() first.

**Comment by djspiewak** [comment]
Well that's not weird or anything…

**Comment by djspiewak** [comment]
I think that rather than initializing the `Signal` with an `emitAll` followed by the `writerSignal`, we need to just take the `writerSignal` and use `process1.feed` to give it a `Set`.  This will ensure that the internal state is managed appropriately.

**Comment by psnively** [comment]
:+1:

**Comment by psnively** [comment]
So how do we get closure on this? Unfortunately, an important project is blocked on it. So I'm really asking "how do we fix, confirm, and release this?"

**Comment by djspiewak** [comment]
@psnively The best first step would be to shoot us a PR fixing the issue.  I'll probably get to it this weekend-ish, but it sounds like it's a higher priority for you.  Unless I'm missing something, the fix should be almost exactly as straightforward as my description of it above.

Making releases is…a challenge.  Really only @pchiusano can do it.  More importantly, we've already broken binary compatibility with 0.7, so this would need to be a full 0.8 release unless we took your fix and backported it to the 0.7 tags (which should be trivial, since we haven't touched `Signal` all that much).  Either way, Paul would need to make a release.

The alternative is doing what I and @alissapajer have been doing, which is to say pushing snapshot releases to bintray.  The downside is that scalaz-stream is a dependency of several other important projects, notably specs2, so this usually has a bit of a cascade effect though.  If you're willing to put in the elbowgrease though, that's a way forward.

Not coincidentally, re-pushing snapshots of everything in the universe is something that I'm in the process of doing right now for various reasons (mostly related to http4s).  Take a look at the `tmp/scalaz-stream-snapshot` branches on many of my forks to see what's involved and/or to steal stuff to hopefully make your life easier.

**Comment by psnively** [comment]
So unfortunately, my experiments with removing the emitAll and adding a process1.feed have been unsuccessful. It also feels wrong to me: there's nothing obviously wrong with the logic as it stands, at least from my reading of the source of `WriterTopic`. Speaking of, `WriterTopic` is a _big_ gnarly state machine, and there's a fun little method buried in it, `startIfNotYet`, that I wonder if we shouldn't be calling after `new WriterTopic`, because otherwise it's unclear to me how that `emitAll` party is supposed to get started. But then, to be honest, I'm not at all sure I understand the whole `W` and `O` thing in `WriterTopic` anyway. Any further advice would be greatly appreciated.

**Comment by djspiewak** [comment]
@psnively No one understands `WriterTopic`...  :-D

Anyway, I can take a look at this over the weekend.  I'll *try* to find some time to get at it sooner.  If @pchlupacek has any time to hop in, he would be better suited than I am.

**Comment by djspiewak** [comment]
@psnively So, fix is up!  The real trick is getting it into your hands in binary form, and honestly I don't know what to tell you on that front.  As I said, @alissapajer and I work off of signed snapshots (from master) that I push to my personal bintray (which is mirrored to our internal nexus).  I don't know how well that would work for you, but it's a start.  I honestly don't know when 0.8 will be released, but it's probably not going to be soon.

**Comment by runarorama** [comment]
@pchiusano Any chance of cutting a release including this in the near future?

**Comment by pchiusano** [comment]
I wasn't planning on it. If you or want to prepare a PR with just the
changes you want to the 0.7a series branch, and it is backwards compatible,
then I'm okay with a point release. I don't want to do a non binary
compatible release other than what we are planning for 0.8 which is at
least a couple months off.

**Comment by djspiewak** [comment]
@pchiusano We've already broken binary compatibility with 0.7/0.7a.  So we can either backport this change to the 0.7 branch and cut a 0.7.1 release, or…uh, snapshots are the only option.

@runarorama You can always [my bintray](https://bintray.com/djspiewak/maven) to your resolvers and use version `3775c7dcdf7b102343aea427d0b0854f3e66d184` ([signer](https://keybase.io/djspiewak)).  It's not a perfect solution, but it works.

**Comment by djspiewak** [comment]
@pchiusano Oh, I misunderstood your comment a bit.  *This* change is backwards compatible, it's just that the changes we've accumulated since 0.7 are not.

**Comment by pchiusano** [comment]
Yep, understood. :)

**Comment by psnively** [comment]
The problem with this (for my team) is that post-0.7a also fixes an issue we encountered when we introduced 0.7a (indirectly, via http4s). I don't know what commit fixes the issue, and since the issue reveals itself as a deadlock, it would be non-trivial to track down. So I'd like to encourage the release of a new version sooner than a couple of months in any way I can. :-)

**Comment by pchlupacek** [comment]
@pchiusano, @djspiewak  how about cutting 0.8 and leave 0.9 for next release? I agree that some fixes in this release are important and fix the eventual oddities. We have to perhaps do better job in back porting these to last release branch next time.

**Comment by djspiewak** [comment]
@psnively The deadlock you reference is almost certainly resolved by [the `njoin` fix](https://github.com/scalaz/scalaz-stream/pull/366).  It wouldn't be hard to backport that fix.

@pchlupacek Given that we're targeting significant changes for the release currently known as 0.8, I would be in favor of making *that* release 1.0 and pushing 0.8 up now (or thereabouts).  Going forward, I would like to propose a versioning scheme which delegates major algebraic changes to the major component of the release number (e.g. version 0.5 *should* have been version 1.0 under that scheme).  Minor algebraic changes (e.g. the `onPreempt` added to `Await` in master) can happen in minor release increments (e.g. 0.7 to 0.8).  Point releases (e.g. 0.7.1) must preserve binary and source compatibility.  Thoughts?

**Comment by pchiusano** [comment]
I still don't really want to do two breaking releases within a couple
months of each other. It's my opinion that the few people that benefits in
the short term should really just temporarily maintain their own fork.

However if someone would like to put together another 0.7 series release, I
am happy to hit 'go' to actually publish it.

**Comment by djspiewak** [comment]
@psnively I would be willing to work with you to help backport some of these (compatible) changes to 0.7a, so we can do an 0.7.1 release.  Otherwise, I've already snapshotted most of the scalaz universe in my bintray, and I'll be continuing to update those snapshots until 0.8 drops since we need these fixes as much as you do.

@pchiusano What do you think of my proposed versioning scheme?  (significant algebraic changes in major release increments, breaking changes and minor algebra in minor release increments, and strictly compatible in point releases)

**Comment by pchiusano** [comment]
@djspiewak The thing I don't like about that scheme is that 0.8 would have to be 1.0. I think 1.0 means something else to most people, and what we've been calling 0.8 is not going to be a "1.0 release". (The version after that hopefully will be, though.)

But yeah, after 1.0, a versioning policy like that sounds sensible. Let's discuss later though. :)

**Comment by psnively** [comment]
@djspiewak Super, thanks! How should we proceed with this? From our end, we apparently need at least the njoin and TopicWriter fixes, but anything else you think we could/should backport we may as well identify and do while we're at it. How can I help?

**Comment by djspiewak** [comment]
@psnively Best way to go about it, I think, would be to branch off of the 0.7a tag and start cherry picking the commits you need.  The binary incompatible stuff should be pretty apparent.  If you get stuck on something, push the branch somewhere and I'll dive in!

Oh also we should open an issue to track this 0.7.1 effort.

**Comment by pchiusano** [comment]
Sounds good to me. Let me know when everything is set to go and I can push
the button. :)
